POST  http://localhost:3000/users
content-type: application/json

{
    "email": "wachiraamos402@gmail.com",
    "password": "amo11063",
    "username": "Amos"
}

###kul
POST  http://localhost:3000/users/login
content-type: application/json

{
  "email": "wachiraamos402@gmail.com",
  "password": "amo11063"
}


###
DELETE  http://localhost:3000/users/4
content-type: application/json


###
GET http://localhost:3000/users
content-type: application/json